# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moviesapp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmoviesapp.proto\x12\nmycrudgrpc\"\x07\n\x05\x45mpty\"e\n\tMovieInfo\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12&\n\x08\x64irector\x18\x04 \x01(\x0b\x32\x14.mycrudgrpc.Director\")\n\x08\x44irector\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\"\x14\n\x04Uuid\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x19\n\x06Status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9c\x02\n\x05Movie\x12\x37\n\tGetMovies\x12\x11.mycrudgrpc.Empty\x1a\x15.mycrudgrpc.MovieInfo0\x01\x12\x33\n\x08GetMovie\x12\x10.mycrudgrpc.Uuid\x1a\x15.mycrudgrpc.MovieInfo\x12\x36\n\x0b\x43reateMovie\x12\x15.mycrudgrpc.MovieInfo\x1a\x10.mycrudgrpc.Uuid\x12\x38\n\x0bUpdateMovie\x12\x15.mycrudgrpc.MovieInfo\x1a\x12.mycrudgrpc.Status\x12\x33\n\x0b\x44\x65leteMovie\x12\x10.mycrudgrpc.Uuid\x1a\x12.mycrudgrpc.StatusBk\n\x1bro.carnei.mycrudgrpc.protosB\x10MyCrudGrpcProtosP\x01Z/github.com/carnei-ro/my-crud-grpc/protos;protos\xa2\x02\x06MYCRUDb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moviesapp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033ro.carnei.mycrudgrpc.protosB\020MyCrudGrpcProtosP\001Z/github.com/carnei-ro/my-crud-grpc/protos;protos\242\002\006MYCRUD'
  _EMPTY._serialized_start=31
  _EMPTY._serialized_end=38
  _MOVIEINFO._serialized_start=40
  _MOVIEINFO._serialized_end=141
  _DIRECTOR._serialized_start=143
  _DIRECTOR._serialized_end=184
  _UUID._serialized_start=186
  _UUID._serialized_end=206
  _STATUS._serialized_start=208
  _STATUS._serialized_end=233
  _MOVIE._serialized_start=236
  _MOVIE._serialized_end=520
# @@protoc_insertion_point(module_scope)
